repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with autopep8
        - "--max-line-length=88"
